[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
tuit-core = { path = "crates/tuit-core" }
tuit-maildir = { path = "crates/tuit-maildir" }
tuit-tui = { path = "crates/tuit-tui" }
